# Generated by Django 2.0.4 on 2018-06-26 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Miss.', 'Miss.'), ('Mrs.', 'Mrs.')], max_length=6)),
                ('designation', models.CharField(choices=[('Prof.', 'Prof.'), ('Senior-Lecturer', 'Senior-Lecturer'), ('Lect1', 'Lecturer-1'), ('Lect2', 'Lecturer-2')], max_length=15)),
                ('personal_information', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
