# Generated by Django 2.0.4 on 2018-06-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='personal_information',
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='field_specialization',
            field=models.CharField(choices=[('geophysics', 'Geophysics')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='qualification',
            field=models.CharField(choices=[('Prof', 'Professor'), ('sl', 'Snr. Lecturer'), ('Lect1', 'Lecturer I'), ('Lect2', 'Lecturer II'), ('al', 'Assistant Lecturer'), ('ga', 'Graduate Assistant')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='designation',
            field=models.CharField(choices=[('Prof', 'Professor'), ('sl', 'Snr. Lecturer'), ('Lect1', 'Lecturer I'), ('Lect2', 'Lecturer II'), ('al', 'Assistant Lecturer'), ('ga', 'Graduate Assistant')], max_length=15),
        ),
    ]
