# Generated by Django 2.0.4 on 2018-06-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_auto_20180626_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='field_specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='qualification',
            field=models.CharField(choices=[('phd', 'PhD'), ('msc', 'Msc'), ('bsc', 'Bsc')], max_length=15),
        ),
    ]
