# Generated by Django 2.0.4 on 2018-06-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_auto_20180626_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Snr. Lecturer', 'Snr. Lecturer'), ('Lecturer I', 'Lecturer I'), ('Lecturer II', 'Lecturer II'), ('Assistant Lecturer', 'Assistant Lecturer'), ('Graduate Assistant', 'Graduate Assistant')], max_length=15),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='qualification',
            field=models.CharField(max_length=15),
        ),
    ]
