# Generated by Django 2.0.4 on 2018-06-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0004_auto_20180627_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturerprofile',
            old_name='field_specialization',
            new_name='field_of_specialization',
        ),
    ]
