# Generated by Django 2.0.4 on 2018-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0005_auto_20180627_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='course_taught',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
