# Generated by Django 2.0.4 on 2018-06-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0009_auto_20180629_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecturerDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='firsthallvenuearrangement',
            name='lecturer_three',
        ),
        migrations.RemoveField(
            model_name='firsthallvenuearrangement',
            name='lecturer_two',
        ),
        migrations.RemoveField(
            model_name='secondhallvenuearrangement',
            name='lecturer_three',
        ),
        migrations.RemoveField(
            model_name='secondhallvenuearrangement',
            name='lecturer_two',
        ),
        migrations.AlterField(
            model_name='secondhallvenuearrangement',
            name='lecturer_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_one_second', to='lecturer.LecturerProfile'),
        ),
    ]
