# Generated by Django 2.0.4 on 2018-06-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=10)),
                ('credit_unit', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LectureDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LectureTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=10)),
                ('credit_unit', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('second_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('third_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('fourth_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('fifth_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('sixth_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('seventh_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('eighth_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('day', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.LectureDay')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('second_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('third_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('fourth_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('fifth_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('sixth_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('seventh_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('eighth_course', models.CharField(blank=True, choices=[('0', '-'), ('1', 'GES 100.1'), ('2', 'GES 102.1'), ('3', 'CHM 130.1'), ('4', 'MTN 110.1'), ('5', 'MTH 120.1'), ('6', 'PYH 101.1'), ('7', 'PHY 102.1')], max_length=10)),
                ('day', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.LectureDay')),
            ],
        ),
    ]
