# Generated by Django 2.0.4 on 2018-06-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180627_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HallVenueArrangement',
        ),
        migrations.AlterField(
            model_name='timetableone',
            name='day',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_first', to='student.LectureDay'),
        ),
        migrations.AlterField(
            model_name='timetabletwo',
            name='day',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_second', to='student.LectureDay'),
        ),
    ]
